apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-eta-deploy
  labels:
    app: healthapp-eta-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthapp-eta-app
  template:
    metadata:
      labels:
        app: healthapp-eta-app
    spec:
      containers:
      - name: healthapp-eta-container
        image: shubhamwak96/myprojectapp1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: healthapp-eta-np-service1
  labels:
    app: healthapp-eta-app1
spec:
  selector:
    app: healthapp-eta-app

  type: NodePort
  ports:
  - nodePort: 310011    
    port: 8080
    targetPort: 8080
